Add accessibility
ulises2607/Portfolio pull request #11
Opened 2023-06-20 22:49 UTC by ulises2607

- improved title
- Images:
              . Fixed header icon
              . Alt on hamb-icon added
              . Alt changed on class social-icon
              . divider alt removed
- Fixed all element positions
- Labels added in the form section

2023-06-20 22:57 UTC, stanleySimeon requested changes
# Hi @ulises2607 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not met all the project requirements, kindly I suggest you make sure your linters check are passed before asking for another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-20 23:28 UTC, Shedrack-Sunday requested changes
Hello @ulises2607    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with checking accessibility features✔️  
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement
- [ ] The requirement was to list all points checked and give an evaluation of either its solved, or what was done to fix it. Based on your review, you missed the following evaluations on the pull request:
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- The basic structure of the page.

- [ ] Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").
- [ ] If you needed to change something, [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148). Please add the links.

### Instructions:
![image](https://github.com/ulises2607/Portfolio/assets/50990925/2e37888f-a28f-4a20-8721-863050a01dd2)



_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-20 23:28 UTC, Shedrack-Sunday commented on index.html
> +        alt=""
- [ ] All images with the `alt` should have an alternative text which is useful for interacting with the page 👍

2023-06-20 23:28 UTC, Shedrack-Sunday commented on index.html
> +      </div>
- [ ] Kindly check my comment on line `46` on the need for the `alt` to be specified with appropriate text 👍

2023-06-20 23:28 UTC, Shedrack-Sunday requested changes
Hello @ulises2607    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with checking accessibility features✔️  
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement
- [ ] The requirement was to list all points checked and give an evaluation of either its solved, or what was done to fix it. Based on your review, you missed the following evaluations on the pull request:
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- The basic structure of the page.

- [ ] Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").
- [ ] If you needed to change something, [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148). Please add the links.

### Instructions:
![image](https://github.com/ulises2607/Portfolio/assets/50990925/2e37888f-a28f-4a20-8721-863050a01dd2)



_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-21 21:18 UTC, shahadat3669 requested changes
Hi Everyone, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
✅ Good PR Title
✅ Good PR Description
✅ Good use of GitHub Flows

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 21:18 UTC, shahadat3669 commented on index.html
> +        <h1>My Recent Works</h1>
Great work so far! 👏  It appears that you're using the `<h1>` tag for each section title. However, it's recommended to have only one `<h1>` tag per webpage for better accessibility. Consider replacing the `<h1>` tag with an appropriate heading tag, such as `<h2>` to `<h6>`, depending on the hierarchy and relevance of the titles within your code. You can refer to the [documentation on heading elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#accessibility_concerns) for more information.

By implementing these suggestions, you'll ensure that your design is consistent and adheres to best practices. Keep up the excellent work! Happy coding! 😊

**_Note that most of the headings in your webpage are not structured well. please consider the same requirement for all headings._**

2023-06-21 22:48 UTC, LionRouge1 approved these changes
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-06-21 23:43 UTC, merged