Details popup window
ulises2607/Portfolio pull request #13
Opened 2023-06-29 16:14 UTC by ulises2607

- Added script to create a popup for the project cards section
- Created a project array
- Added buttons to the card project in the desktop version.

2023-06-29 17:52 UTC, Strangeal requested changes
Hi @ulises2607, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 17:52 UTC, Strangeal commented on style.css
> +}
- [ ] Kindly consider adjusting your project details pop-up as it's currently not matching that of the `Figma` design and also has some empty spacing which doesn't help in creating a good user experience. To help create a good user experience kindly consider the below suggestions:
  - [x] In the below video you can see there is a huge empty space at the `top` and `bottom` of your `model` which is a problem and due to that, the `model` is not visible when a user clicks on the see more `button` on a project. To `fix` that consider removing the `top: 200%` and setting it to maybe `top: 1%` instead.
  
  - [x] Also, Note that your `model` is supposed to be at a `fixed` position that way when users scroll on the page when the `model` is opened the background of the page only moves but not the model itself. To `fix`  this consider a `position: fixed` instead of `position: absolute`.
  - [x] Additionally, consider adding a `width` to your model as it's currently covering the entire page in your design but is not the same as the `Figma` design. To fix this consider adding a `width: 90%` or any of your choice and also add `margin: auto` which will help your model to get centered to the middle of the screen. 
  - [x] Consider adding a `height: 98vh` or any of your choice so that the model will not touch the base of the screen but rather leave some space below it to make the design look more stunning and accurate like that of the `Figma` design. 
  - [ ] It would be better if you consider adding `overflow-y: scroll` as it's going to help users scroll to see all content of the model should incase the model content overflows on some screen sizes.
  See below for more details on the video:
  
  
  
https://github.com/ulises2607/Portfolio/assets/107192076/d772f7e8-f281-4f37-9bcc-b5ca32d8b487

2023-06-29 17:52 UTC, Strangeal commented on style.css
> +}
- [ ]  Kindly consider adjusting your project model pop-up as it's currently not matching that of the `Figma` design and also has some empty spacing which doesn't help in creating a good user experience. To help create a good user experience kindly consider the below suggestions:
  - [ ] Kindly consider aligning your `model` image and content in a row instead of a column as shown in the `Figma` design.
   - [ ] For the content of your `model` to stay in its parent container, we need to define a `height` here so that the content of the model doesn't overlap the `height` of the container because we defined a `height: 98vh` in our first comment. To fix this consider setting a `height: 85vh` or any of your choice.
   - [ ] For the content of the `model` not to overlap as mentioned above consider removing the `justify-content: center` property so that the content is aligned from the `top` of the `model` to the `bottom` during screen resize.
   - [ ] Kindly consider removing the `padding` you have set as the spacing around your model content is too much.
   - [ ]  Kindly consider adjusting the spacing below the model `title` and the `technologies` as well because it is too much and doesn't match that of the `Figma` design.
   - [ ] Additionally, consider adding adding `margin: auto` which will help your model content to get centered in the middle of its parent container. 
 See below for more details:
   <table>
<tr>
<th align=“middle”>Figma design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="577" alt="Screenshot 2023-06-29 at 17 33 40" src="https://github.com/ulises2607/Portfolio/assets/107192076/90f9fb3c-bcab-4616-af8d-244689ef8e28">
</td>
<td>
<img width="543" alt="Screenshot 2023-06-29 at 17 32 57" src="https://github.com/ulises2607/Portfolio/assets/107192076/9905bacd-80b7-4f79-bb45-c8a629bf51e3">
</td>
</tr>
</table>

2023-06-29 17:52 UTC, Strangeal commented on style.css
> +}
- [ ] Kindly consider adhering to the `Figma` design as much as possible. Your model on desktop screens is supposed to be aligned in a `row` instead of `column`. Please consider changing your direction from row to column so your design matches the original one. See below for more details:
   <table>
<tr>
<th align=“middle”>Figma design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="577" alt="Screenshot 2023-06-29 at 17 33 40" src="https://github.com/ulises2607/Portfolio/assets/107192076/90f9fb3c-bcab-4616-af8d-244689ef8e28">
</td>
<td>
<img width="543" alt="Screenshot 2023-06-29 at 17 32 57" src="https://github.com/ulises2607/Portfolio/assets/107192076/9905bacd-80b7-4f79-bb45-c8a629bf51e3">
</td>
</tr>
</table>

2023-06-29 23:36 UTC, 1GORDON requested changes
##
## Hi @ulises2607, and @GhausAliKhan ✋

Good job so far!

## Highlights!
- Descriptive Pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 23:36 UTC, 1GORDON commented on style.css
> +}
Great job team 🤝

- [ ] As requested by the previous reviewer, kindly ensure your design doesn't touch the base of your screen. You may consider following the suggestions by the previous reviewer to fix this issue. Kindly apply this to both mobile and desktop screens.
- Your design
![your-base](https://github.com/ulises2607/Portfolio/assets/63917725/c906b9ed-26da-42e1-9df2-100b090e59d8)

2023-06-30 18:16 UTC, sumairq approved these changes
### Hi @ulises2607 , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 18:40 UTC, merged